name: Lint

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: 10.x

      - uses: bahmutov/npm-install@v1

      - name: Pre-generate docs
        run: yarn run pregenerate

      - name: Check for modified files
        run: |
          if [[ `git status --porcelain --untracked-files=no` ]]; then
            echo "Tracked files were modified by 'yarn run pregenerate'"
            exit 1
          else
            exit 0
          fi

      - name: Run linter
        run: yarn run lint
